services:
  postgres:
    image: postgres
    container_name: postgres-pizza-2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres 
      POSTGRES_DB: pizzastore
    ports:
      - "5425:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: nest_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DB_URL: postgres://postgres:postgres@postgres:5432/pizzastore
      NODE_ENV: development
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app  # Mount local files for live reload
      - /app/node_modules  # Prevent overwriting node_modules
    command: sh -c "npm run start:dev"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

volumes:
  postgres_data:
    driver: local

